merge_method: dare_ties
base_model: typhoon-ai/typhoon-s-thaillm-8b-instruct-research-preview
models:
  - model: ThaiLLM/ThaiLLM-8B-IQ
    parameters:
      weight: 1.0
      density: 0.5
  - model: ThaiLLM/ThaiLLM-8B-ToolUse
    parameters:
      weight: 0.3
      density: 0.5
parameters:
  normalize: false
  int8_mask: true
dtype: bfloat16
tokenizer:
  source: ThaiLLM/ThaiLLM-8B-IQ
chat_template: auto
